### ISSUE TITLE
Accuracy fuction is wrong

### ISSUE THREAD

**Issue by xiaomaxiao** [szad670401/end-to-end-for-chinese-plate-recognition#1]
tag number is 7 , but  for 4 in accuracy fc.

**Comment by szad670401** [comment]
the output number in my project is 7.
Did you make a mistake?

**Comment by xiaomaxiao** [comment]
@szad670401 https://github.com/szad670401/end-to-end-for-chinese-plate-recognition/blob/master/train.py#L127

**Comment by szad670401** [comment]
This is my mistake. I will fix it.
thank you.
